class YelpFields(object):
    BUS_ID = 'business_id'
    REV_TEX = 'text'
    STARS = 'stars'

    # group ids there are used to produce summaries
    EXCLUDED_GROUP_IDS = {'2JsLzYF8rUalwpm5LDEcog', '6C_8Mh4lmLc_QEs3hHleBg',
                          '5VXsbrqyJx0a4iaa43RNFA',
                          '5iHctUjkQTGwEvOaBkwMRQ', '87YsVbCN_kfzheY79Fzjkg',
                          '3m2XZFVraCiqjgLxHi5MdA',
                          '7w99ECXyIR32SKLyMKOLaw', '5mJlO3oCw_4vvbq1qM6OEg',
                          '-1UMR00eXtwaeh59pEiDjA',
                          '65GMvjjrsvyR9pxxAys7qg', '0NgePUfXd2TG0kWgsQRq0A',
                          '5EIuCcoHY2evAhFMBV6G6g',
                          '82YGtjc5KKikNiqBZ33qzw', '4uZkUUbl6dr_bjmS2QNnbA',
                          '0GVu1xLqxbUQLfSCp25OGQ',
                          '2jqUYcKMYZXnpxNTkORJgQ', '7v91woy8IpLrqXsRvxj_vw',
                          '86stmK3Vm2f5W6PdyvuLrQ',
                          '1e6Xtmd4BetTnsoRCK3J5g', '0M2Us97NRafGL6Tojx2gbw',
                          '7gjYJ6leqm2IMJXNpKvIlw',
                          '57_msr8gjNakjGO-1f6B_g', '82hYL5WPQpvxg8ekDsB83A',
                          '5vAe61D-AAjGZBFA4Ep8mQ',
                          '5ID843Ti7L0aa7BQIeXNaw', '7GGJlp1aWfcXGQz6q7SkXQ',
                          '4SxQLZ2EcjlFRG6BvCi0iA',
                          '1Z4_zSITNVQ_Bt027R0S1g', '4oWEqa3paBylDXRfTPB-bA',
                          '065c76tt1dXBNmoGBymUgQ',
                          '0Hcks5q-DgJbDlmEWolx4A', '4KtHdcaZgJNZvbRgs5edKQ',
                          '3S471NOBFUzQY7YqCImKBQ',
                          '1xO2LvScpcMfl2BNm1aISg', '7mMxJjeZqnN_nOhWhyU-Vg',
                          '6qDRqHWqf0EeHupSUEBfKg',
                          '7wst00GRGs8qsuf2QtsnaA', '35fWtS1LZkaZ-ooKupJ1XA',
                          '5XVabANkehj7oH-Z7YZkwg',
                          '7qo6rqDjlHds8ObxzxBD4A', '53jjJCXpXSRaHfu_ZJePRA',
                          '7VYFL_s1HK1vOU-dzyW1Ew',
                          '3l5TusofKjr8rk6-DDtuoQ', '31acLzszeCCpeXmyAnoTdg',
                          '01Ov9eDxKRY5k6ImMdiWLQ',
                          '8MWiywu09bhLWIpzVaD4gw', '4nLqlBBt6jcvphkIQxz0gQ',
                          '5k34OJo3BsEaoyMsW86eZg',
                          '5QkfMhF0KgK28hMYOKngRw', '1KhBzrqmU164bss64jR5uA',
                          '7k5F32LULnjplZVQdI4DdQ',
                          '6u-x45q0ETB7SQTAAuKSHw', '1aj4TG0eFq6NaPBKk6bK7Q',
                          '4p6Wce7Ed707QS2-yQkvZw',
                          '13-n6Gm0AK0QK28iatttWQ', '4Wou6LarHqefHP21qRu0Ag',
                          '3cbsPfoUUrysf-M8FI_0IA',
                          '6B-sZzuNYnVz5sk2c4EfHA', '6LtbAtQKXWFj7QcqBnr6SA',
                          '2S9t90Q0qZWCV7X_u0rxZQ',
                          '0EpnzIpeFvhISkxMTIv9WA', '3hmoQIAUaYF9u_QaxfjwwQ',
                          '6uV3KMOo8YQofuNUs4D9pA',
                          '-8R_-EkGpUhBk55K9Dd4mg', '5CJOaZc8Muu8WothauxQ4g',
                          '3BGzRYh6GQbZz3LGAGb-sQ',
                          '6ExIH5FoPyMRhtz4p-2K1g', '5vTdyRqZ-wnOZ4ZANrzFOQ',
                          '5CTmFgqxx7nl8jzQK2Du-A',
                          '2z7xERz1Nonyw8Kjr4SffA', '0bjFYstj8USMzEV4ZQldjA',
                          '2Xix4Iv6gdj3F6fbJX3zgA',
                          '2um9bzTSvD3f2tkdBoA38g', '6g2EQgi1QiXcp9TvbyG-Ig',
                          '41ojNbT0vv2Rtto8yPcwSg',
                          '7QSFLU0AGAUqwnQWg3qHqQ', '0Rni7ocMC_Lg2UH0lDeKMQ',
                          '2tfMXjOotr1r168mVttUmQ',
                          '2mdF-c66TY3eSyTVI4GhQg', '5HGO1CxM0qPIS_u4L90Bvw',
                          '4-ErDo1ggAg0DWrVwPa-IQ',
                          '0p0PqX7Zsm_0lvXzEWpwWA', '0XoTT540HMB_5q4Exj8yGA',
                          '2tC8oReqFUT0_uVQ3kHePA',
                          '59OgPGGzKFYqwSG_U06kuA', '4M09MJwxRx8utAgEntFVrQ',
                          '0G1y7uV7w1D2uziS4Lt_Dw',
                          '-R2kwt0qMnzwEdAfXPvkXg', '7u0DEiUxTO3rAJ7C8ak46Q',
                          '7aOaX7QASqa8ab8eAx8TEA',
                          '4HoCAPiFH2BFznYxGR7sjQ', '5ts_r4K6y103zNXt0k6nEg',
                          '5AzGqv0jjRMXrcRIE1zCvg',
                          '2QznyHGF0PuiYkrl5RU66A', '4DVqziHGABcYUUw_E36c5g',
                          '06Vts51gZrtBnFMs6sBPbA',
                          '1TTQ41NqKks69GltQSQNIA', '0TYd9CxJMqaqO6svyWym6A',
                          '5mu4SWwVTgNUXw0lWLaoZw',
                          '3bVc_IDRyAXpg__qkEEXyw', '309bnXTHirKMU6wz1HwRjQ',
                          '0ihQJhd_-nUP1p01NBDjLQ',
                          '6I27BTuHI5PMvOBG4WS8NQ', '1rebduwtmrHQhl32djRS7A',
                          '5QNXZcclknB2PkfeN7FJWQ',
                          '4qQVf2lt-47VcQ4v54PEXQ', '29e_OB7jRf7-5Tdn7_bd_g',
                          '7xfeQhen2wLnvFuQNvmTAg',
                          '5Lcit9Zt6TF9bmKoFMhF0g', '5lZpyuWjC7L9uJfLfqIQ_w',
                          '55X2pom73IhiP19UFXpfPA',
                          '0kB69ewW3BVse8EhU4kxrQ', '8JcCvA_92PVcNQUh1J_TaA',
                          '2r6UD7ExSMrK0LGeglquDA',
                          '1QwX7Cgkm6KnlcGNDTh6EQ', '67Pa_CtXthgJzXfY8JzLDQ',
                          '5s51wuld6gIIiERpDU4yrw',
                          '2Q89PhkcyT9uZnQORmqMKg', '3I7xY7DjWearTz7d4TGdbw',
                          '8DPZWbP6gKaBsGoAFQkSaA',
                          '0QBFtNNj9RIggZGeivcbEg', '6qKhUQwyMLBl9ehwB-cfxQ',
                          '3fdtp-bzoE4ZgTakkcEBzQ',
                          '3HmrkEZQWaemS2aPoe-xJA', '5BSrguKmbBb9W4R5IvbW7w',
                          '4kDLEb1OgE7IrO54lCkn3A',
                          '333W59XcrXZsJlnBAAx5mQ', '0PMMhCAz2S5dmcA9mJ3dRg',
                          '1nQMj-F3Oz3IeP9h10CNIA',
                          '6TDdpon8LosFXvjL9QJdYg', '4cWrtMvfj-tomyEPgP7KFg',
                          '3A0xvZPEUduT0GE9VxxUUQ',
                          '4ugJ4F8jDJ9-2dEiZ47wLg', '7OQ7lhIsjLSmf-3012LAuw',
                          '5b_n_RXYQtNf9b2d-O4SzA',
                          '0oh91u-VcUopMsdHJvF-CQ', '806kkDGaRCJ4lZLRcEf-iw',
                          '373HGZUJm47MupH8QBx8Zg',
                          '7yTtTjsZLi5Ef1vsr6ZPTw', '7o61DDMJ1noIlDbjY-McEA',
                          '1ZgqJjtb91E9tOKhKrzsuw',
                          '4POPYEONJpkfhWOMx_PyGg', '8FUzCm4Q13MJMX7N6ftmQw',
                          '3xEO9oyGqfO_O8eSlxYTBA',
                          '4gXdyihRiytmXEAfqLNMBw', '5u27mhDjcJ4Y7QbDhRyaXg',
                          '1GA01-VWTAkV72huVT409g',
                          '3XE-poXz9CeDao-Q7pqkTw', '0jHZk9RrKh0uRhTRW1XIqQ',
                          '6nmlclYyyLyH5EGLUpsmjw',
                          '13RpfoJXpRseXTW_RyEyPQ', '5OqrwhtZ3mcmUSwLINZTWQ',
                          '2YZ0gKvOsrdbZ7LKdxRhxA',
                          '07jQarxKd_8J_AJHD5YBqQ', '749MsdV9v1SijXaLrY23pw',
                          '1x8_aJQ-iqvymhRK3SNbLg',
                          '80TTAvMtRsPPFtFFnXgskA', '7owvf-6q5pmVQXTxLI6Wqg',
                          '6pQ1DpZo6zygNc3qTch-iA',
                          '7jl9EJQCGBiTyXTDXMsRIw', '5WJOM9DefIvLOIrntDIv-A',
                          '74C1z6cqEdvJVgETTcEodw',
                          '0kPm1zEpeXFRg8D2phqgCQ', '6jDD-Z8QcsKTdIDWwM8gog',
                          '41H6zhehn6vY_b0f2JPuwA',
                          '7ABOYoF6DeUnX-jTYH14wA', '0BbRoMwVTZgYV1oqgtsHOw',
                          '0mb-rhWhjrlyiNFGrH_FbQ',
                          '50KEvLtQl9Vv4YE1vs681Q', '-zuJkmIjdRahT_yHED-62g',
                          '0XHMciYfPq7HzEiLCknaCA',
                          '5PZefPGncZH6AWMqPY2m9g', '4oUBoG5Ui48wUSvy2rS4VQ',
                          '4iACB0ppsvwA2mFvLJoNbA',
                          '0uwQIGlKICIYuRtayVnh7g', '4yAvytbVKHqSYAo3mkI9OA',
                          '4c19YWOjPmbFUK4-V2GEvg',
                          '1_Dg-GguWatioW4mvFQKQA'
                          }
